check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
helm.version: v3.12.3
cni.plugins.version: 1.3.0
k9s.version: 0.26.7
crictl.version: v1.28.0
stern.version: 1.26.0
containerd.version: 1.6.8
ingress.nginx.version: 1.8.1
kubernetes.dashboard.version: 2.7.0
metallb.version: 0.13.10
