check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
helm.version: v3.9.4
cni.plugins.version: 1.1.1
k9s.version: 0.26.3
crictl.version: v1.24.2
stern.version: 1.22.0
containerd.version: 1.3.9
ingress.nginx.version: 1.3.0
kubernetes.dashboard.version: 2.6.1
metallb.version: 0.13.4